# Artificial Neural Network

# Importing the libraries

In [6]:
import numpy as np
import pandas as pd
import tensorflow as tf
tf.__version__

'2.21.0'

# Part 1 - Data Preprocessing

# Importing the dataset

In [16]:
from datasets import load_dataset

dataset = load_dataset("d0r1h/customer_churn")

# Convert the train split to a Pandas DataFrame
data = dataset["train"].to_pandas()

# Convert "Error" values to NaN
data = data.replace("Error", np.nan)

# Select columns 0, 1, 3, 4, 13, 14, 15, 16 for X
X = data.iloc[:, [0, 1, 3, 4, 12, 13, 14, 15]].values

# Select the last column for y
y = data.iloc[:, -1].values

print(X)
print(y)

[[18 'F' 'Village' ... 300.63 53005.25 '17']
 [32 'F' 'City' ... 306.34 12838.38 '10']
 [44 'F' 'Town' ... 516.16 21027.0 '22']
 ...
 [23 'F' None ... 154.94 38127.56 nan]
 [53 'M' 'Village' ... 482.61 2378.86 '20']
 [35 'M' 'Town' ... 79.18 2189.68 nan]]
[0 0 1 ... 1 0 0]


In [17]:
# Taking care of missing data
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
columns_to_impute = [0,4,5,6,7]
imputer.fit(X[:, columns_to_impute])
X[:, columns_to_impute] = imputer.transform(X[:, columns_to_impute])
print(X)

[[18.0 'F' 'Village' ... 300.63 53005.25 17.0]
 [32.0 'F' 'City' ... 306.34 12838.38 10.0]
 [44.0 'F' 'Town' ... 516.16 21027.0 22.0]
 ...
 [23.0 'F' None ... 154.94 38127.56 15.976715237411563]
 [53.0 'M' 'Village' ... 482.61 2378.86 20.0]
 [35.0 'M' 'Town' ... 79.18 2189.68 15.976715237411563]]


# Encoding categorical data
# Label Encoding the "Gender" column

In [18]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 1] = le.fit_transform(X[:, 1])
print(X)

[[18.0 0 'Village' ... 300.63 53005.25 17.0]
 [32.0 0 'City' ... 306.34 12838.38 10.0]
 [44.0 0 'Town' ... 516.16 21027.0 22.0]
 ...
 [23.0 0 None ... 154.94 38127.56 15.976715237411563]
 [53.0 1 'Village' ... 482.61 2378.86 20.0]
 [35.0 1 'Town' ... 79.18 2189.68 15.976715237411563]]


# One Hot Encoding the "Region" column

In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [2,3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[0.0 0.0 1.0 ... 300.63 53005.25 17.0]
 [1.0 0.0 0.0 ... 306.34 12838.38 10.0]
 [0.0 1.0 0.0 ... 516.16 21027.0 22.0]
 ...
 [0.0 0.0 0.0 ... 154.94 38127.56 15.976715237411563]
 [0.0 0.0 1.0 ... 482.61 2378.86 20.0]
 [0.0 1.0 0.0 ... 79.18 2189.68 15.976715237411563]]


# Splitting the dataset into the Training set and Test set

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling

In [21]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Part 2 - Building the ANN

# Initializing the ANN

In [22]:
ann = tf.keras.models.Sequential()

# Adding the input layer and the first hidden layer

In [23]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding the second hidden layer

In [24]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding the output layer

In [25]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Part 3 - Training the ANN

# Compiling the ANN

In [26]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Training the ANN on the Training set

In [27]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
925/925 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8126 - loss: 0.3852
Epoch 2/100
925/925 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8457 - loss: 0.2869
Epoch 3/100
925/925 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8481 - loss: 0.2825
Epoch 4/100
925/925 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8482 - loss: 0.2805
Epoch 5/100
925/925 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8470 - loss: 0.2792
Epoch 6/100
925/925 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8474 - loss: 0.2780
Epoch 7/100
925/925 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8471 - loss: 0.2771
Epoch 8/100
925/925 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8489 - loss: 0.2762
Epoch 9/100
925/925 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8492 - loss: 0.2758
Epoch 10/100
925/925 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8495 - loss: 0.2753
Epoch 11/100
925/925 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8481 - loss: 0.2752
Epoch 12/100
925/925 ━━━━━━━━━━━━━━━━━━━━

# Predicting the Test set results

In [28]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

232/232 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
[[1 0]
 [0 0]
 [1 1]
 ...
 [1 1]
 [1 1]
 [1 1]]


# Making the Confusion Matrix

In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[3079  313]
 [ 863 3144]]


0.8410596026490066